### ISSUE TITLE
Getting errors quite regularly in practice

### ISSUE THREAD

**Issue by ChrisSargent** [simonireilly/observatory-github-action#332]
We have this running as a CI job, it probably gets run 8 or 10 times a day and currently is failing about 50% of the time. I've attached some screenshots of the logs. It looks like maybe observatory is doing some throttling but then the retries are too close together and it gets blocked, not quite sure though.

Happy to try to help with a PR if you have an idea where to start looking?

Thanks,

Chris

<img width="1435" alt="Screenshot 2022-05-04 at 17 01 32" src="https://user-images.githubusercontent.com/12176122/166711420-8c9b6bd1-77f4-487e-b976-d314fe90c707.png">
<img width="1303" alt="Screenshot 2022-05-04 at 17 05 36" src="https://user-images.githubusercontent.com/12176122/166711433-3f2215f5-afc7-4298-87ca-9aafb38ecaa7.png">

**Comment by simonireilly** [comment]
Hi Chris,

Thanks for this.

I've seen this myself and had retries put at 30 within the action in order to try and counter that.

I do think Observatory throttles, and in their docs they recommend running your own version of the tool - I believe via docker.

Let me do a deeper dig.

All contributions welcome of course, the code for this project is fairly light, it's just exec'ing the observatory CLI.

**Comment by simonireilly** [comment]
At first glance I would say the problem lies in the underlying CLI, here:

https://github.com/mozilla/observatory-cli/blob/a4635a41522dee9bec5f3dd21063d95422166d58/index.js#L124-L183

But following on from that it looks like here:

https://github.com/simonireilly/observatory-github-action/blob/8ede7d2376147396669b1954283532703a1aa95b/src/tools/observatory-runner.ts#L25-L37

In this action I might try something different - I'll implement an exponential backoff logic here - because I think the linear single second retry is not configurable:

https://github.com/mozilla/observatory-cli/issues/25

**Comment by simonireilly** [comment]
@ChrisSargent I have cut a beta at 

Can you try:

```yaml
- name: Observatory Github Action
  id: observatory
  uses: simonireilly/observatory-github-action@v0.1.1-beta.1
  with:
    web_host: https://example.com
```

Would be good to know if this increases the stability by reducing the total number of requests.

**Comment by simonireilly** [comment]
Should be closed by https://github.com/simonireilly/observatory-github-action/releases/tag/v0.1.1

Re-open if it continues
